# Generated by Django 5.2 on 2025-04-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="is_green",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="updated_at",
        ),
    ]
