# Generated by Django 5.2.8 on 2026-01-20 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0002_remove_accommodation_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accommodation",
            name="is_green",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
