# Generated by Django 5.2 on 2025-04-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="created_at",
        ),
    ]
